---
become_override: false
silent: false

ocp4_workload_ansible_automation_platform_tmp_dir: /tmp/{{ guid }}
ocp4_workload_ansible_automation_platform_tmp_kubeconfig: "{{ playbook_dir }}/kubeconfig"
#ocp4_workload_ansible_automation_platform_tmp_kubeconfig: >-
#  /var/tmp/kubeconfig
  #{{ ocp4_workload_ansible_automation_platform_tmp_dir }}/.kube/config

ocp4_workload_ansible_automation_platform_project: "aap"
ocp4_workload_ansible_automation_platform_app_name: "aap"
ocp4_workload_ansible_automation_eda_app_name: "edacontroller"
ocp4_workload_ansible_automation_platform_display: "ansible-automation-platform"
ocp4_workload_ansible_automation_platform_description: "Ansible Automation Platorm"
# OCP bearer token lifecycle for use as an AAP cred - default to 2 weeks
ocp4_workload_ansible_automation_platform_ocp_token_lifecycle: 1209600
ocp4_workload_ansible_automation_platform_subscription_channel: "stable-2.4"

ocp4_workload_ansible_automation_platform_admin_password: >-
  {{ common_password | default(aap_controller_admin_password) }}

ocp4_workload_ansible_automation_platform_manifest:
  inject: true 
  url: https://rhserverless.s3.ap-southeast-2.amazonaws.com/manifest_aap.zip 
  username: jonsnow
  password: got2023


deploy_eda_controller: True
