---
- name: RETRIEVE WORKER NODE DETAILS FROM KUBERNETES NODE
  hosts: localhost
  gather_facts: no

  collections: 
    - kubernetes.core
  
  tasks:
  - name: GET WORKER NODE DETAILS
    kubernetes.core.k8s_info:
      kind: Node
      namespace: default 
