download_url: https://galaxy.ansible.com/download/kubernetes-core-2.4.0.tar.gz
format_version: 1.0.0
name: core
namespace: kubernetes
server: https://galaxy.ansible.com/api/
signatures: []
version: 2.4.0
version_url: https://galaxy.ansible.com/api/v2/collections/kubernetes/core/versions/2.4.0/
